### ISSUE TITLE
There is nothing to worry about

### ISSUE THREAD

**Issue by betawarrior12** [Fik-Creator/Fik-Creator-1#1]
Fikayo I finally found you

**Comment by Fik-Creator** [comment]
Yes,welcome to this page but please don't use my name call me Fik-creator

**Comment by Fik-Creator** [comment]
You can check my novel website on Just-Novels.blogspot.com

**Comment by betawarrior12** [comment]
Ok thanks didn't have time to read the novel
YOU DID A NICE JOB REVIEW YOUR USE OF WORDS OK FIK-CREATOR
FROM BETAWARRIOR12
